### PR TITLE
add babel plugin styled-components

### PR DESCRIPTION
**Pull request by viankakrisna**
This minifies the CSS in template tag literal and add nicer component names in React dev tools :)

master:
screen shot 2017-07-23 at 2 41 02 pm

add/babel/plugin/styled-components:
screen shot 2017-07-23 at 2 39 15 pm

https://github.com/styled-components/babel-plugin-styled-components

### CODE REVIEW

**Comment by CompuIves** [comment]
Ah this is great!! Thanks!

Could you add yourself to the contributors list by running `npm run add`?

Then it's ready to merge 😄 .

**Comment by viankakrisna** [comment]
hmm, I'm new to this `all-contributors thing`, it errors out:
screen shot 2017-07-23 at 7 37 43 pm
same thing happened when i do `npm run add -- viankakrisna code`
screen shot 2017-07-23 at 8 02 21 pm
Will dig more what causes this...

**Comment by CompuIves** [comment]
Hmm, that's strange. It seems like you do have the required changes in git. Could you commit the changed files (`.all-contributorsrc` and `README.md`)? Then I can check if everything is in order.

**Comment by viankakrisna** [comment]
@CompuIves done!

**Comment by CompuIves** [comment]
Seems all good! Just waiting for the tests to clear and I'll merge it.

Very nice, thank you! We're one contributor richer 😄 . Expect a contributor badge somewhere in the couple next weeks.

**Comment by viankakrisna** [comment]
Great! I've got a lot of contribution ideas, hope I can make it in the coming future :). Thank you for open sourcing this 👍

**Pull request merged**
