### PR TITLE
Fix space in EntryContainer

### PR DESCRIPTION
**Pull request by elrumordelaluz**
It is a `css` fix that allow to view the _Buttons_ when hovering the _EntryContainer_ in case the name of the project is too long.

**Current**
codesandbox

**Fix**
codesandbox_2

**Checklist**:

- [ ] Documentation N/A
- [ X] Tests N/A
- [ X] Ready to be merged 
- [X ] Added myself to contributors table

### CODE REVIEW

**Comment by CompuIves** [comment]
Woooow this is great!! Could you fix the conflicts (I think just adding yourself again is sufficient)? Would love to merge this quickly, thanks for fixing this!

**Comment by elrumordelaluz** [comment]
There was an `undefined` returned when I run `yarn add-contributor` the first time with an exit:

```
error Command failed with exit code 1.
```

Same when I run it again
all-contribs

Let me know if there's a _workaround_, happy to help fix these conflicts asap.

**Comment by CompuIves** [comment]
Yap, I think I've seen that issue before. I think the files still get generated, but it returns a wrong error code. Does it generate new files for you? Otherwise you can just remove the contributors changes from the PR and I'll add you manually.

**Comment by CompuIves** [comment]
Ah, went ahead and fixed the merge conflict 😄

**Comment by elrumordelaluz** [comment]
I see right now the notifications, cool thank you @CompuIves!

**Pull request merged**
