### PR TITLE
[WIP] Connect Emmet to Monaco

### LINKED ISSUE #194: Add emmet support

### PR DESCRIPTION
**Pull request by satyarohith**
**What kind of change does this PR introduce?**
Enables emmet support 

**What is the current behavior?**
Emmet is not connected to the editor

**What is the new behavior?**
We have Emmet support as before :smile: 

closes #194

### CODE REVIEW

**Comment by satyarohith** [comment]
Oops! Did not notice this error. I learned to open `console`after every modification :smile:, I will get back after I implement `tokenize`.

**Comment by satyarohith** [comment]
Hi @CompuIves, I'm quite confused about how stuff is working right now.
We have two files `enable-combi-emmet.js` and `enable-emmet.js`.
The text expansion and edits in the editor are done via `enableCombiEmmet(editor, monaco);`
but we also have some logic in `enable-emmet.js`.  I couldn't figure out what exactly is it doing?
It seems like it sets the position of the cursor and also attempts to edit the editor according to emmet, I might be wrong here.

Coming to `tokenize` I implemented this way but I was getting error which I was unable to figure out and also cursor positioning does not work.
```js
const token = monaco.editor.tokenize(
   model.getLineContent(lineNumber),
   model._languageIdentifier.id
)[0];
```
loging the token without [0] I got this
screenshot from 2018-07-24 14-46-07

and the error after implementing the above
screenshot from 2018-07-24 14-32-36

If I'm not wrong,The main problem according to what I know is we are unable to place the cursor according to the expansion of elements.
Thanks for taking time to read this Ives, point me where I'm doing wrong.

**Comment by CompuIves** [comment]
Ahh, yes it's quite a mess. We have two implementations of Emmet, one of those was the initial implementation and the other one was added later because the first one broke if I remember correctly. It seems like the error is related to a bad call within Monaco, which possible could be because some services in Monaco are mocked to work in the browser.

I think the main focus is to make `enable-combi-emmet.js` work first, I believe that one works the best. Does that one throw any errors?

**Comment by CompuIves** [comment]
That makes a lot of sense @satyarohith. Great to hear that it works! I think it can be done with something `editor.cursor.setPosition`.

**Comment by satyarohith** [comment]
Hi @CompuIves I got cursor placement working but when expanding multiple elements they are not formatted as expected.
singleelement
multiele
I think the culprit might be `expandText`.
Do you have any Idea about this?

**Comment by abhinayar** [comment]
Hey guys,

Seems to still be an issue! Not sure what the status is on this, is a huge thing for me if I want to move my workflow to CodeSandbox. Let me know if there's anything I can do to help!

Best,
Abhi

**Comment by SaraVieira** [comment]
@CompuIves @satyarohith Same, what is left so this can be merged? If not a lot can we merge into some other branch so other people can work on it ?

**Comment by satyarohith** [comment]
I'm sorry for not being active.
Indentation and cursor placement for multiple expansions don't work
properly.
I'm quite busy now due to exams so would love to know if anyone is
interested to take a look.
Thanks for bearing with me.

**Comment by CompuIves** [comment]
I implemented Emmet directly in our language server now, it should feel very smooth 
screen shot 2018-10-23 at 03 52 42.

Thanks for the work @satyarohith, I appreciate the research behind it! Good luck with the exams!

**Pull request closed without merging**
