### PR TITLE
Handle .prettierrc file at root

### PR DESCRIPTION
**Pull request by ValentinH**
**What kind of change does this PR introduce?**
It adds support for `.prettierrc` file placed at the root of the sandbox. It updates the Prettier preferences when the `.prettierrc` is saved.

Idea from @kentcdodds at https://twitter.com/kentcdodds/status/944817103814692864

Staging demo: http://pr419.cs.lbogdan.tk/s/rj733y8y6o

This is a kinda raw experiment but it's working fine so far but I already have some improvements in mind: 
- keep the default values for the keys not provided by the `.prettierrc` so the preferences UI is not broken. Like below for the "Tab width":
image

### CODE REVIEW

**Comment by CompuIves** [comment]
Wow that was fast! Thank you so much!

I'm thinking that we could maybe do the parsing of `.prettierrc` right before we prettify. If there's a valid file we use that and otherwise we use the preference. I think the function of prettify is in the same file.

**Comment by ValentinH** [comment]
You mean that we should not overwrite the preferences with the file content but just check if the file exists when prettyfying?

**Comment by ValentinH** [comment]
I wasn't sure about how to implement this so I'm open to all ideas :)

**Comment by CompuIves** [comment]
> You mean that we should not overwrite the preferences with the file content but just check if the file exists when prettyfying?

Yes exactly, I think that's the most intuitive way.

**Comment by ValentinH** [comment]
Yes I thought about that but I wasn't sure where do to this? Could you point the file to edit? :)

**Comment by ValentinH** [comment]
And then maybe show a message in the preferences panel to indicate that the prettier preferences are currently overwritten by the .prettier.

**Comment by CompuIves** [comment]
> Yes I thought about that but I wasn't sure where do to this? Could you point the file to edit? :)

We run prettify here: https://github.com/CompuIves/codesandbox-client/blob/master/packages/app/src/app/store/entities/sandboxes/modules/actions.js#L49-L50. You can get the `.prettierrc` by getting all modules for the sandbox and doing something like this:

`modules.find(m => m.directoryShortid == null && m.title === '.prettierrc')`. Then use that instead if it exists.

> And then maybe show a message in the preferences panel to indicate that the prettier preferences are currently overwritten by the .prettier.

This is a **great** idea!!

**Comment by ValentinH** [comment]
@CompuIves I have updated following your advice.

However, about my suggestion for showing a message in the case we are overwriting the Prettier config, I'm not sure how to achieve this.
I'm seeing in the state that there can be several sandboxes so how can I get the one currently displayed (except looking at the url)?

**Comment by CompuIves** [comment]
Perfect! Implementation is also very good.

> However, about my suggestion for showing a message in the case we are overwriting the Prettier config, I'm not sure how to achieve this.

Hmm, yes. We will move to a new state system this month per #389, then that would be possible. For now I'd suggest adding a message like: "This configuration can be overwritten by a .prettierrc in the sandbox." to the prettier preferences window. Then this PR is ready to be merged and deployed!

**Comment by ValentinH** [comment]
Ok, sounds good ! 
I'll complete this tomorrow, now it's Christmas time! 

Merry Christmas!!

**Comment by ValentinH** [comment]
Done ;)

**Comment by CompuIves** [comment]
Works perfectly!! Thank you very much!

**Comment by ValentinH** [comment]
\o/

**Pull request merged**
