### PR TITLE
simplify preferences store

### PR DESCRIPTION
**Pull request by viankakrisna**
again, not tested, but this should make adding a preference less boilerplate-y

### CODE REVIEW

**Comment by CompuIves** [comment]
Holy macaroni, we were just talking about this less than two hours ago! 😱

**Comment by CompuIves** [comment]
This looks *great*! Let me take it for a test run 🚗 .

**Comment by CompuIves** [comment]
Hmm, it doesn't work yet, don't know why yet. 

I have a way for you to enable the preferences 😄 .

Run this in the console:

```
store.dispatch({type: 'SET_CURRENT_USER', data: { jwt: 'aefawef'}})
```

**Comment by viankakrisna** [comment]
ah yes, that's what I needed! debugging....

**Comment by viankakrisna** [comment]
should be working now, thanks for the preferences enabler!

**Comment by CompuIves** [comment]
Niiiice! There is one last change you need to make in `Prettier.js`. That one is still using the old system.

**Comment by CompuIves** [comment]
Oooh this is so great, now settings will be a breeze to add!

**Comment by CompuIves** [comment]
Nice! Okay, one last quick review and it'll be ready to merge.

**Comment by CompuIves** [comment]
Yup, this is great. Thanks again (for the 3rd time today!).

**Pull request merged**
