### PR TITLE
Change babel preset to env preset.

### PR DESCRIPTION
**Pull request by jsonnull**

### CODE REVIEW

**Comment by CompuIves** [comment]
Great! Thanks! One question: shouldn't we add `babel-preset-env` to the devDependencies in package.json? Not sure, maybe it works differently.

Could you also add yourself to the contributors by running:

```
npm run add
```
?

**Comment by jsonnull** [comment]
Good call, I also added the preset to the devDependencies section.

The overlap shouldn't hurt—I much prefer to keep dependencies up-to-date with runtime deps and devDependencies up-to-date with build-time deps, so this is good.

Also, contributors updated, thank you! The script did have a bad exit status but the update went through—is this something that needs to be looked into?

**Comment by CompuIves** [comment]
Great, thanks! I think the author (Kent) is aware of the exit code of contributors, maybe I need to update dependencies 😅 .

**Comment by CompuIves** [comment]
Oh hmm, it seems like the commit of adding to `devDependencies` is empty (https://github.com/CompuIves/codesandbox-client/pull/215/commits/7fa8249cdfd27db79e40bec33aa01f9e81c1014b).

**Comment by jsonnull** [comment]
Strange!

I added another commit which includes the preset in devDependencies.

**Comment by CompuIves** [comment]
Okay! Thanks for the PR!

**Pull request merged**
