### PR TITLE
move all requests from rawgit.com to serve from jsdelivr.net

### PR DESCRIPTION
**Pull request by sairam**
**What kind of change does this PR introduce?**
updation of urls from rawgit CDN to jsdelivr CDN

**What is the current behavior?**
URLs are fetched from cdn.rawgit.com 

**What is the new behavior?**
No, change in the behavior

**Checklist**:
- [x] Documentation - N/A
- [x] Tests
- [x] Ready to be merged 

Reason: rawgit.com is getting shutdown

### CODE REVIEW

**Comment by Haroenv** [comment]
fixes #1180

**Comment by SaraVieira** [comment]
@CompuIves Can i merge this ? :D

**Comment by SaraVieira** [comment]
sorry i don't know git

**Comment by CompuIves** [comment]
Thanks for the contribution @sairam! Could you merge this PR with the latest `master`? I think then we cna merge it in. 😄

**Comment by sairam** [comment]
@CompuIves looks like one of the check was failing. I have not spent time looking into it

**Comment by CompuIves** [comment]
That's okay! It's our IE11 check failing on CRA template, since CRA recently dropped support. Thanks for the merge, I'll take a look now!

**Comment by CompuIves** [comment]
Seems like everything works! Thanks for the contribution!

**Pull request merged**
