### PR TITLE
Preserve scroll position

### PR DESCRIPTION
**Pull request by chakrihacker**
closes #536

### CODE REVIEW

**Comment by chakrihacker** [comment]
Why am I getting deployment error??

**Comment by CompuIves** [comment]
That's strange. I'll double check with @lbogdan!

**Comment by CompuIves** [comment]
Whoop! Thanks @lbogdan  😄

**Comment by chakrihacker** [comment]
Just to know what error you encountered with my pr

**Comment by lbogdan** [comment]
@chakrihacker It was an issue with the build server, had nothing to do with your PR. :-)

**Pull request merged**
