### PR TITLE
[WIP] Remove inline styles

### PR DESCRIPTION
**Pull request by SaraVieira**
**What kind of change does this PR introduce?**
Remove most inline styles

Count:
Start: 404
Current: 285

### CODE REVIEW

**Comment by SaraVieira** [comment]
240

**Comment by SaraVieira** [comment]
146

**Comment by CompuIves** [comment]
NICe!

**Comment by SaraVieira** [comment]
80

**Comment by SaraVieira** [comment]
Done!!

Website is breaking because of 

```
styled-components.browser.esm.js:226 Uncaught Error: It seems you are interpolating a keyframe declaration (bcCCNc) into an untagged string. This was supported in styled-components v3, but is not longer supported in v4 as keyframes are now injected on-demand. Please wrap your string in the css\`\` helper (see https://www.styled-components.com/docs/api#css), which ensures the styles are injected correctly.
```

Things like this:

```
export const Container = styled.div`
  position: absolute;
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  background-color: ${props =>
    props.theme['sideBar.background'] || props.theme.background};
  color: ${props => props.theme['sideBar.foreground'] || 'inherit'};
  height: 100%;
  width: 100%;
  overflow-y: overlay;
  overflow-x: auto;

  > div {
    ${fadeIn(0)};
  }
`;
```

**Comment by SaraVieira** [comment]
So the whole website is broken now so I will close this at least for now

**Pull request closed without merging**
