### PR TITLE
Improve formatting of string arguments in integrated console

### PR DESCRIPTION
**Pull request by viankakrisna**
**What kind of change does this PR introduce?**
enhancement

**What is the current behavior?**
with 
```
console.log('BEFORE', JSON.stringify(variable, null, 2));
console.log('AFTER', JSON.stringify(variable, null, 2));
```
codesandbox io_s_x7ll8n372p

**What is the new behavior?**
codesandbox io_s_x7ll8n372p 2
codesandbox io_s_x7ll8n372p 1

**Checklist**:

- [ ] Documentation N/A
- [ ] Tests N/A
- [x] Ready to be merged 
- [x] Added myself to contributors table

### CODE REVIEW

**Comment by lbogdan** [comment]
You can simply do `console.log('some text', someVariable)` to get a much nicer display of `someVariable`.

**Comment by viankakrisna** [comment]
@lbogdan yea, but it's a nested object and i'm too lazy to click on the arrows :D

**Comment by CompuIves** [comment]
Hmm, I noticed that we need to change the logic altogether. I just checked in Chrome console and it seems that if all vars are strings, then we need to concatenate them:

screen shot 2017-11-18 at 16 15 28

Maybe we can do that combined with this change?

**Comment by viankakrisna** [comment]
i see, will see if i can implement that 👍

**Comment by viankakrisna** [comment]
pushed incorrect implementation because i can't test it locally (bad connection, need to upgrade yarn for workspace and install dependencies) 😅

**Comment by viankakrisna** [comment]
weird, can't run it locally even after upgrading yarn and installing dependencies. I'll see this at a later time.

**Comment by CompuIves** [comment]
Yep, I got the same thing. I'm fixing it now, should be fixed in 1.5 hours.

**Comment by CompuIves** [comment]
Fixed @viankakrisna! 😄

**Comment by viankakrisna** [comment]
@CompuIves updated!

with this:
```
const styles = {
  fontFamily: 'sans-serif',
  textAlign: 'center',
};
console.log('APP:', JSON.stringify(styles, null, 2))
```
comes this:
screenshot from 2017-11-20 11-41-26

**Comment by CompuIves** [comment]
Great!! Merci 😄

**Pull request merged**
