### PR TITLE
add preference button to header

### LINKED ISSUE #105: Move "preferences" button to Sandbox header
Current location of the "Preferences" button in the user dropdown is un-intuitive and hard to find. This can be remedied by moving the button toggle to the right side of the Sandbox header.

### PR DESCRIPTION
**Pull request by Tushkiz**
fixes #105

### CODE REVIEW

**Comment by CompuIves** [comment]
Thanks a lot @Tushkiz! Do you have a screenshot of how it would look like?

Also, could you add yourself to the contributors list of CodeSandbox? You can do this by running `npm run add`.

**Comment by Tushkiz** [comment]
Unable to do 'Sign in with Github' on my local setup, although here is the screenshot.

preferences

Opens up same popup as that of UserMenu

**Comment by CompuIves** [comment]
I'll merge it now, if you're interested in one more contribution: I'm looking for someone that wants to do this: https://github.com/CompuIves/codesandbox-client/issues/106. Since you're already familiar 🙂 . Also absolutely no problem if you don't have time!

**Comment by Tushkiz** [comment]
Assign #106 to me, I would love it 😬

**Comment by CompuIves** [comment]
Thanks @Tushkiz! I found out that I can only assign you if you respond to the issue 😅 .

**Pull request merged**
