### PR TITLE
Fix expanding of devtools in the editor...

### PR DESCRIPTION
**Pull request by lbogdan**
…when url contains expanddevtools=1 parameter.

It's kinda naive, but it works.

### CODE REVIEW

**Comment by lbogdan** [comment]
Btw, while fiddling with Redux devtools, I've noticed we're not sending a `SET_DEV_TOOLS_OPEN` action on open, only on close.

**Comment by CompuIves** [comment]
Hmm, I think this breaks the `Open Console` quick action. When you open Quick Actions and select 'Toggle Console' it doesn't open the console anymore.

**Comment by lbogdan** [comment]
Well, I was kinda expecting it to break something. :man_shrugging: Maybe we should unify them?

**Comment by gautamarora** [comment]
@lbogdan - This is really cool, and I look forward to this landing.

Just dropping an issue in here as it seems related and possibly one that will be fixed by your PR: https://github.com/CompuIves/codesandbox-client/issues/353

**Comment by lbogdan** [comment]
Closing this for now as it's full of conflicts and we probably need another approach. Left #353 open and labeled it as a bug.

**Pull request closed without merging**
