### PR TITLE
Prevent the sidebar resizer to be over the preferences

### PR DESCRIPTION
**Pull request by ValentinH**
As reported in #83.

Before:
image

After:
image

**What kind of change does this PR introduce?**
Bug fix

**What is the current behavior?**
The sidebar resizer was displayed over the preferences panel.

**Checklist**:

- [x] Documentation N/A
- [x] Tests (did find existing test for this part)
- [x] Ready to be merged 
- [x] Added myself to contributors table

### CODE REVIEW

**Comment by CompuIves** [comment]
This is great, thanks! Could you quickly test if notifications are still above the modal? You could run something like, `store.dispatch({ type: 'ADD_NOTIFICATION', id: 800, endTime: Date.now() + 4 * 1000, notificationType: 'notice', title: 'test' })`;

**Comment by ValentinH** [comment]
Newbie question: where can I run this code? Do I need to update the code?

**Comment by CompuIves** [comment]
I think it should work if you run it in the Chrome Devtools (alt+command+J for mac) and entering the code.

**Comment by ValentinH** [comment]
`store` is undefined there :/

**Comment by ValentinH** [comment]
But let me update the app to test ;)

**Comment by ValentinH** [comment]
Notifications are fine \o/:
image

**Comment by CompuIves** [comment]
Greaaat! Nice! Thanks 😄

**Pull request merged**
