### PR TITLE
Update mobx-state-tree to version 3.3.0

### PR DESCRIPTION
**Pull request by krvajal**
**What kind of change does this PR introduce?**
Updated the version of `mobx-state-tree` to version 3.3.0. 

**What is the current behavior?**
The user is unable to remove a tag from the list of tags by clicking the delete button ( See #1063)

**Checklist**:

- [ ] Documentation N/A
- [ ] Tests 
- [x] Ready to be merged 
- [ ] Added myself to contributors table

### CODE REVIEW

**Comment by krvajal** [comment]
I would like to add a test to verify that this works as expected and catch any future regressions.

**Comment by CompuIves** [comment]
This is very nice! I have to admit that our testing system is very bad, we do have Jest tests but nearly not enough, so thanks for adding tests! That would be very helpful.

The part that should be tested is Cerebral, I think this is a good article on testing: https://cerebraljs.com/docs/api/test. This is the sequence that we'd need to test:

https://github.com/CompuIves/codesandbox-client/blob/ea37dbc3b6bb230ac580974f1a2e764a5494f3d3/packages/app/src/app/store/modules/workspace/sequences.js#L100-L107

**Comment by krvajal** [comment]
I am having some trouble with the `ensureOwnedSandbox` action because it is calling `forkSandbox` and this then checks for the `editor.currentId` which is null. Is there a way to create a new sandbox by calling a signal or something in the controller?
```js

it("can add a tag", () => {

  const controller = Controller(rootModule);
  // it this editor.currentSandbox.owned == true is not true
  // the forkSandbox sequence will be executed
  // also this will make all the sequence fail
  expect(controller.getState("editor.currentId")).toBeNull()

  expect(controller.getState('workspace.tags')).toEqual({tagName: ""})
  const tagChanged = controller.getSignal("workspace.tagChanged")

  tagChanged({tagName: "tag_01"})
  expect(controller.getState('workspace.tags')).toEqual({tagName: "tag_01"})
  const tagAdded = controller.getSignal("workspace.tagAdded");
  tagAdded()
})


```

**Comment by CompuIves** [comment]
Hmm yeah I can see that as a problem. We can change `ensureOwnedSandbox` to get another prop like `{ force: true }` and it will skip its behaviour. Something like this:

```
export const ensureOwnedSandbox = sequence('ensureOwnedSandbox', [
  when(state`editor.currentSandbox.owned`, props`force`, (owned, force) => owned && !force),
  {
    true: [],
    false: forkSandbox,
  },
]);
```

This seems like the easiest solution, mostly because we use this sequence so many times.

**Comment by CompuIves** [comment]
Heya! I'm getting a bit more requests for this bugfix, so I think we should merge this one in first and focus on the tests in another PR. Thanks a lot for this contribution 😄

**Pull request merged**
