### PR TITLE
Added chat on discord option and removed Feedback button

### LINKED ISSUE #275: Add chat on discord in navigation menu
I am thinking to add chat on discord link in navigation bar, so users can come to discord and discuss about issues. I am also thinking to remove feed back button and replace with chat on discord. This may increase user engagement. please throw your thoughts @CompuIves , @lbogdan

### PR DESCRIPTION
**Pull request by chakrihacker**
**What kind of change does this PR introduce?**
Feature

**What is the current behavior?**
Sending Feedback to server

**What is the new behavior?**
redirecting users to discord

**Checklist**:

- [x] Ready to be merged yes
- [x] Added myself to contributors table

closes #275

### CODE REVIEW

**Comment by CompuIves** [comment]
Great, thanks @chakrihacker! Let's wait for Discords response before merging this in.

**Comment by CompuIves** [comment]
Hey @chakrihacker, I got response from Discord. We won't get VIP for now, so let's just merge this in. Could you do a last merge with master so I can test it on staging?

**Comment by chakrihacker** [comment]
@CompuIves Sorry, I didn't understand your statement, this pull request is committed on master. can you please explain if I am wrong or I didn't understand 😄

**Comment by CompuIves** [comment]
Yes, absolutely! We recently had a change on master that allows us to see live previews of PRs, but we need to put the latest version of master on the PR. This means that you need to:

1. Checkout to master
2. Pull the latest changes from master
3. Checkout the branch of the PR
4. `git merge master`
5. and push it 😄 

This will put recent changes of master in this PR.

**Comment by chakrihacker** [comment]
updated pr, thanks for brief explanation :smile:

**Comment by CompuIves** [comment]
Great, thanks @chakrihacker!

**Pull request merged**
