### PR TITLE
Issue #547: Fixed Preview Navigator to act as normal browser on handling url history.

### PR DESCRIPTION
**Pull request by Williammer**
This PR is to fix issue #547

### CODE REVIEW

**Comment by lbogdan** [comment]
Hey @Williammer, thanks for your PR!

Unfortunately this seems to break SPAs, as it will reload the frame when you press the back / forward navigation buttons in apps that use the html5 history api; for an example see https://codesandbox.io/s/zq380r0wqx vs. http://pr548.cs.lbogdan.tk/s/zq380r0wqx .

**Comment by lbogdan** [comment]
(for reference, [this](https://github.com/CompuIves/codesandbox-client/pull/198) is the PR that refactored preview history handling)

**Comment by Williammer** [comment]
@lbogdan Thanks for your information! 
Seems like there's some tradeoffs there, I'll check out the related threads in more details.

**Comment by lbogdan** [comment]
Hey @Williammer , any updates on this? I'm thinking about closing this PR (and the corresponding issue #547 ), as the behavior of clearing the history on preview reload is expected.

**Comment by Williammer** [comment]
Sorry, I'll close it.

**Pull request closed without merging**
