### PR TITLE
Homepage: visual switch for web applications section on mobile

### PR DESCRIPTION
**Pull request by duivvv**
**What kind of change does this PR introduce?**

homepage change

changed position of Tailored for web applications intro as discussed here https://twitter.com/CompuIves/status/931253159871295488

### CODE REVIEW

**Comment by duivvv** [comment]
Fixed it this way, do you have a suggestion so we don't need to change text twice.
Should I create a new component (maybe <Intro/>) in /Frameworks so we can change the text once?

Let me know and I'll do the changes + the all contributors step.

**Comment by CompuIves** [comment]
Super! Hmm yes, I can think of 2 approaches we can do here:

1. Wrap the two elements in a `display: flex` block. We can then do `flex-direction: column-reverse` for mobile and `flex-direction: column;` for higher. This feels like the best solution, but I'm not sure if it's possible with the current layout.
2. Extract the selection to a component and use the `Media` like you do here.

Would be great to have option 1, but only if it makes sense with the current layout. Otherwise 2 is the best option, as it's very clear.

Thanks a lot for the contribution! Great to have a new contributor for CodeSandbox 😄

**Comment by duivvv** [comment]
I also agree 1 would be the best option, taking a look how much impact it has.

**Comment by duivvv** [comment]
@CompuIves Think I nailed it.  🎉

**Comment by CompuIves** [comment]
That's great!! I can merge it in tomorrow, when I'm back at my MacBook. Thanks a lot!

**Comment by duivvv** [comment]
Sorry about the multiple contributor commits.

I thought it didn't work, but apparently it did :)

**Comment by CompuIves** [comment]
This is great, @duivvv. Thanks! Merging it in now, welcome to the contributors 😄 .

**Comment by duivvv** [comment]
No problem, glad I could help

**Pull request merged**
