### PR TITLE
Update CodeFund embed script

### PR DESCRIPTION
**Pull request by coderberry**
This is a feature and doc update.

The current CodeFund embed script is using the legacy (deprecated) API and URL, which has not been whitelisted with AcceptableAds.com.

**What is the new behavior?**

This PR updates the API endpoint and URL to enable whitelisting and in-app configuration.

I also updated the links on the README and contributors to use the new URL: codefund.app.

**Checklist**:

- [x] Documentation
- [ ] Tests (N/A)
- [ ] Ready to be merged 
- [ ] Added myself to contributors table 

I was unable to test this locally. Please test the new implementation prior to merge. This can be done by going to a sandbox unauthenticated and viewing the ad in the bottom left.

### CODE REVIEW

**Comment by SaraVieira** [comment]
Hey
From what I can see it doesn't seem to be working:

http://pr1492.cs.lbogdan.tk/s/539q87vor4

**Comment by CompuIves** [comment]
Hmm, might this be because it's tested on a different domain?

**Comment by CompuIves** [comment]
Oh, nevermind. It works  for m!

**Comment by SaraVieira** [comment]
Might be my adblocker ahah

Can I merghe?

**Comment by CompuIves** [comment]
Yep! Ready for merge!

**Pull request merged**
