### PR TITLE
Added new upload image functionality

### PR DESCRIPTION
**Pull request by wuweiweiwu**
**What kind of change does this PR introduce?**
Feature!!

**What is the current behavior?**
#100 currently no way to upload images.

**What is the new behavior?**
Added upload image icon besides create file and create directory. 

on click, pop up file dialog and then the user can chose an image to upload. File is created with original name in the project. 

request sent with `isBinary: true`

images are hosted by imgur :)

**Checklist**:

- [ ] Documentation
- [x] Tests
- [x] Ready to be merged 
- [x] Added myself to contributors table 

Here is what it looks like!

giphy

### CODE REVIEW

**Comment by CompuIves** [comment]
Wow, this looks really nice!! I can do a full review after next Monday, we have a big release planned that day.

**Comment by wuweiweiwu** [comment]
@CompuIves Awesome! I look forward to it. We can also expand the functionality to upload all kinds of files. images, js source, json, etc.

**Comment by wuweiweiwu** [comment]
@CompuIves bump. I will fix the merge conflicts. When will this be reviewed? Thanks!

**Comment by CompuIves** [comment]
Hey @wuweiweiwu, I'm sorry for the late reply. I was working overtime for the Vue Amsterdam talk this time. Now I'm free again though.

I've been looking a bit at ways to make file upload work and I really like how [Snack](https://snack.expo.io/) does it, they open this modal:

screen shot 2018-02-18 at 21 59 51

And let you drop files. I was thinking that we could open up an upload endpoint in CodeSandbox that you could call then. Then we'd return the URL to the relevant file.

I'm sorry to barge in with these ideas, I hope you're still motivated to work on this 😄. If you are, maybe it would be cool to chat to bounce some ideas around in the Discord (https://discord.gg/KE3TbEZ).

**Comment by wuweiweiwu** [comment]
@CompuIves No probs! I was hoping to generalize the image upload process to other files as well :) Just joined the discord

**Pull request closed without merging**
