### PR TITLE
Fix vue-router <router-link> in hash mode

### LINKED ISSUE #595: Hash routes not working
https://codesandbox.io/s/pk8807zz0

### PR DESCRIPTION
**Pull request by lbogdan**
Fixes #595 .

Test: http://pr810.cs.lbogdan.tk/s/pk8807zz0 .

### CODE REVIEW

**Comment by CompuIves** [comment]
Nice! In general it would be nice if we could find a way to make hash links work, I remember having similar issues with react router in hash and I believe it was mentioned here too: #572.

**Comment by lbogdan** [comment]
`react-router` already worked in hash mode, see http://pr810.cs.lbogdan.tk/s/2wow48xvnj . And #572 was about not "scrolling" the page to the element with the id equal to the link hash when clicking on a hash link (which I'll look into shortly).

**Comment by CompuIves** [comment]
Ahh, that makes sense. Thanks for the clarification and the PR 😄

**Comment by lbogdan** [comment]
To go a bit into detail, `react-router` it's fully based on `hashchange` events, while `vue-router` also listens for `click` events on hash links, which we're hijacking, so that's why we only need the workaround for `vue-router`.

**Pull request merged**
