### PR TITLE
Community templates

### PR DESCRIPTION
**Pull request by CompuIves**
This is a combination of #665 and #683. I'm using this to see the complete diff and do testing. I will deploy this to staging too 😄

### CODE REVIEW

**Comment by CompuIves** [comment]
cc @nicknisi and @mstijak. I think it would be great if both templates would be based of a GitHub repository. Then I'll change the logic of the importer to detect `CxJS` and `Dojo` so we can do final proper testing on staging.

**Comment by nicknisi** [comment]
Yeah, that makes sense!

**Comment by mstijak** [comment]
@CompuIves The CxJS template is available at https://github.com/codaxy/cxjs-codesandbox-template. It should be enough to detect `cx` package dependency. Please note that `react` will also be listed in dependencies as CxJS uses React for rendering.

**Comment by nicknisi** [comment]
@CompuIves Any ideas on when you might be planning to merge this? Not trying to rush at all, just trying to get an understanding your timeline!

**Comment by CompuIves** [comment]
I've put everything on staging now! I'm planning to merge it today.

If you're interested in helping with testing, send your IP to me via Discord or something, I'll add you to the whitelist on our staging server 😄

**Comment by CompuIves** [comment]
Did a bunch of testing, looks good! One thing I'm worrying a bit about is the amount of cubes on the homepage. I'm going to do a code review now and decide about the cubes after that. But it's definitely certain that we'll have this live today! 🎉

**Comment by CompuIves** [comment]
Okay! Everything is ready to merge in after the checks are green and ready to deploy. I decided to keep the cubes on the homepage, but will probably remove some cubes in 2 days after the initial announcement. The reason for this is that every cube takes quite a lot of performance (5 big box-shadows per cube, with transforms) and I'm afraid that our bounce rate will increase if we make it very hefty.

Planning to use this GIF for the announcement:


cx-dojo-xs-small

But bigger of course :smile:

**Pull request merged**
