### PR TITLE
Allows opening tests by default with share link

### LINKED ISSUE #958: Allow opening tests by default with share link
# Share link option for opening the tests.

Add a "Show tests (instead of browser preview)" option to the share link modal.

screen shot 2018-07-13 at 9 16 48 am

### PR DESCRIPTION
**Pull request by satyarohith**
**What kind of change does this PR introduce?**
This PR helps us to have an option to set Tests view instead of Browser view when sharing sandboxes.

**What is the current behavior?**

**What is the new behavior?**
shareviews

**Checklist**:

- [x] Documentation
- [ ] Tests
- [x] Ready to be merged 
- [x] Added myself to contributors table 

closes #958

### CODE REVIEW

**Comment by satyarohith** [comment]
@CompuIves let me know whether this is useful since we can also achieve this from sandbox config files. :)

**Comment by CompuIves** [comment]
Yes! This is what we need! 😄 

Could you also add the options to our docs? https://github.com/CompuIves/codesandbox-client/blob/master/packages/homepage/content/docs/2-embedding.md

**Comment by satyarohith** [comment]
Everything is done, Ives! :smiley:  Let me know if anything is missing.

**Comment by CompuIves** [comment]
This is almost done! The last thing we need to do is make it work in the embed, which can be done by setting the proper property here: https://github.com/CompuIves/codesandbox-client/blob/0fe309992d04fe0fc958c0125210893a90e53c73/packages/app/src/embed/components/Content/index.js#L436.

**Comment by satyarohith** [comment]
@CompuIves It works :tada:  
Right now, preference is given to URL option if both config file and URL option are set.
Let me know what do you think? :smile:

**Comment by CompuIves** [comment]
This is perfect @satyarohith, thanks a lot for the help! I'll let the build run now and merge it in as soon everything turns green. 😄🎉:shipit:

**Comment by kentcdodds** [comment]
Thanks!

**Pull request merged**
