### PR TITLE
Fix resizer showing over modals #83

### PR DESCRIPTION
**Pull request by vueu**

### CODE REVIEW

**Comment by CompuIves** [comment]
Thanks! I can test this somewhere this evening, when I have a laptop. I'll keep you posted!

**Comment by CompuIves** [comment]
Ah, I remember doing the `z-index: 30` there because I wanted to show this highlight on hover:

screen shot 2017-08-02 at 10 32 38

There must be a way to make the hover still show and not overlap on the other UI elements. 🤔

**Comment by vueu** [comment]
Ah, yes. My issue was with the share modal. For some reason I could not get the share modal to show over the separator unless z-index on the separator was 0, although the settings modal worked fine. I'll definitely look into this more when I get the chance.

CSS is weird 😛

**Comment by Arthelon** [comment]
@CompuIves Isn't it just a matter of sequencing the respective z-indexes so that the resizer appears above other elements but below the modal?

**Pull request closed without merging**
