### PR TITLE
Update manifest.json

### PR DESCRIPTION
**Pull request by lifeiscontent**
Update size to match actual asset size.

this also fixes an issue not allowing chrome to "Add to HomeScreen" from the application tab in chrome dev tools.

**What kind of change does this PR introduce?**

**What is the current behavior?**

**What is the new behavior?**

**Checklist**:

- [ ] Documentation
- [ ] Tests
- [x] Ready to be merged 
- [x] Added myself to contributors table

### CODE REVIEW

**Comment by lifeiscontent** [comment]
how do I add myself to contributors table?

**Comment by CompuIves** [comment]
Oh this is great! Thank you @lifeiscontent. You can add your self by running `yarn add-contributor`.

**Comment by lifeiscontent** [comment]
@CompuIves added more icons so codesandbox can now be added to home screen on chromebook 🎉

**Comment by lifeiscontent** [comment]
@CompuIves this is ready to be merged!

**Pull request merged**
