### PR TITLE
Replaced condition with regex

### PR DESCRIPTION
**Pull request by Piterden**
**What kind of change does this PR introduce?**
Regex https://regex101.com/r/xKBMVQ/1

**What is the current behavior?**
Conditions

**What is the new behavior?**
Matching

**Checklist**:

- [ ] Documentation
- [ ] Tests
- [x] Ready to be merged 
- [ ] Added myself to contributors table 

@CompuIves please tell me, if you need such of changes, I can do it in some time...

### CODE REVIEW

**Comment by CompuIves** [comment]
Thanks for the PR! 

It's good to make this condition smaller, but I think this will make it harder to read/understand. The if statement version is more clear in which loaders are added for which lang attribute. Would like to hear the opinion of others here as well.

**Comment by Piterden** [comment]
That's why I am asking )

**Comment by lbogdan** [comment]
I was just about to say the same. Especially there's no performance (or any other) benefit here.

**Comment by Piterden** [comment]
Ya, RegEx'es are just awesome. We could place a link to the RegEx editor in a comment near each RegEx, then it might play the teaching role for those who interested it...

**Comment by lbogdan** [comment]
Closing this as no noticeable benefits, also the file belongs to the [vue-loader](https://github.com/vuejs/vue-loader) fork.

**Pull request closed without merging**
