### PR TITLE
Support react-native-web in create-react-app preset

### PR DESCRIPTION
**Pull request by JulianMayorga**
Create react app does the same in https://github.com/facebookincubator/create-react-app/blob/bd682de1f6b71ea4192b14f66c3bc22e658b5b87/packages/react-scripts/config/webpack.config.dev.js#L106

**What kind of change does this PR introduce?**

Supports React Native Web by aliasing all `import ReactNative from 'react-native'` to `import ReactNative from 'react-native-web'`.

**What is the current behavior?**

Apps made with React Native Web don't work. An error message appears:
```
DependencyNotFoundError
Could not find dependency: 'react-native'
```

**What is the new behavior?**

Apps made with React Native Web work.

**Checklist**:

- [ ] Documentation
- [ ] Tests
- [x] Ready to be merged 
- [x] Added myself to contributors table 

Thank you for making CodeSandbox!

### CODE REVIEW

**Comment by CompuIves** [comment]
This is perfect @JulianMayorga! Thank you very much, LGTM! :shipit:

**Comment by JulianMayorga** [comment]
Great, thanks so much @CompuIves!

Quick question, when do changes like this get to production?

**Comment by CompuIves** [comment]
They should be live now 😄

**Comment by JulianMayorga** [comment]
Continuous deployment FTW 😸

I see it's working perfectly in here: https://codesandbox.io/s/github/wizardry-io/metrotranvia-mendoza/tree/c2f6054315e8cde562ca330654bd953135bd4178

Thanks again!

**Pull request merged**
