### PR TITLE
Codesandbox refactor to Cerebral and Mobx-state-tree

### PR DESCRIPTION
**Pull request by christianalfoni**
So we have gotten to a point now where we can officially start sharing the progress and give more information about "the big refactor". This video introduces some background and conceptual changes: https://youtu.be/7Z4hInb7LmA .

The following remaining refactors are identified:

- [x] pages/CLI - simple
- [x] pages/Profile - medium
- [x] pages/index.js - simple
- [x] containers/integrations/Github - simple
- [x] containers/integrations/Zeit - simple
- [x] containers/modals/SignOutNotice - simple
- [x] containers/modals/ZenModeIntroduction - simple
- [x] containers/Navigation - simple
- [x] containers/UserMenu - simple
- [x] containers/ContextMenu - simple
- [x] containers/SignInButton - simple
- [x] Key bindings - complex
- [x] Codemirror - complex
- [x] Embed - complex
- [x] local storage handling - complex

When done, let the bug hunt begin :-)

### CODE REVIEW

**Comment by Guria** [comment]
@christianalfoni staging is broken:
image

**Comment by lbogdan** [comment]
@Guria @christianalfoni That's because of https://github.com/cerebral/codesandbox-client/blob/113af7b5eb10fc32b83701b3440759867ff2a048/packages/app/src/app/controller.js#L11, should check if `Devtools` is `null`.

**Comment by christianalfoni** [comment]
Ooops, thanks :)

**Comment by lbogdan** [comment]
@christianalfoni It would be nice for devtools to be enabled on staging, you can use process.env.STAGING bool for that: https://github.com/CompuIves/codesandbox-client/blob/master/packages/app/config/env.js#L35 .

**Comment by christianalfoni** [comment]
Cool, updated it! The devtools I showed in the video is not released quite yet. Will be shortly :)

**Comment by lbogdan** [comment]
Ok, it works!
@christianalfoni Can we do something about those re-connections? The console messages are kind of annoying.

**Comment by christianalfoni** [comment]
Ah, yes, I can turn off reconnect :)

**Comment by CompuIves** [comment]
I guess we can close this now :)

**Pull request closed without merging**
