### PR TITLE
Add VuePress template

### PR DESCRIPTION
**Pull request by vicbergquist**
**What kind of change does this PR introduce?**
VuePress starter template feature

**What is the current behavior?**
No VuePress 😞 

**What is the new behavior?**
Get started with VuePress in CodeSandbox

**Checklist**:

- [ ] Documentation
- [x] [Importer](https://github.com/codesandbox/codesandbox-importers/pull/30)
- [x] Tests
- [x] Ready to be merged 
- [x] Added myself to contributors table 

Feels like I'm way in over my head, but hope this will work! 😃 
Would love to use VuePress with CodeSandbox in future projects and talks I have planned.

Not sure if I need to update any documentation, but from what I can tell I don't..?

### CODE REVIEW

**Comment by SaraVieira** [comment]
It works as seen here: https://codesandbox.io/s/github/vicbergquist/codesandbox-vuepress/tree/master/

**Comment by vicbergquist** [comment]
> It works as seen here: https://codesandbox.io/s/github/vicbergquist/codesandbox-vuepress/tree/master/

OH MY GOD! That's amazing, thank you!!

**Comment by SaraVieira** [comment]
@CompuIves @lbogdan The view does not seem to reload, any idea why?

**Comment by lbogdan** [comment]
Yes, it's because the webpack dev server HMR websocket tries to connect to localhost:

image

**Comment by vicbergquist** [comment]
Also, I'm trying to update the default file that is opened (
e0b8d4b), not sure if I have the right approach :(

For the reload issue and https://github.com/CompuIves/codesandbox-client/pull/1652#issuecomment-476319958, how can I help fix this?

**Comment by lbogdan** [comment]
@vicbergquist You'll have to configure webpack devserver to connect the HMR socket to the right URL. It's a combination of getting the `host`, `disableHostCheck` (and probably other settings?) right: https://webpack.js.org/configuration/dev-server/ .

I can also take a look at it somewhere this week.

**Comment by egoist** [comment]
@ulivz we need to fix it here: https://github.com/vuejs/vuepress/blob/759195de7fc7caf1e5a50c80d449b2c5dfa45cd5/packages/%40vuepress/core/lib/node/dev/index.js#L237 or at least allow user to customize it, the webpack-dev-server client is trying to connect `localhost` but we should use `location.host` or simply `/`

**Comment by lbogdan** [comment]
Fixed here https://codesandbox.io/s/948mvov384 , by replacing `host: this.host` in https://github.com/vuejs/vuepress/blob/759195de7fc7caf1e5a50c80d449b2c5dfa45cd5/packages/%40vuepress/core/lib/node/dev/index.js#L223 with `host: '0.0.0.0'`.

**Comment by CompuIves** [comment]
Hey! This is awesome, let me know when it's ready to merge!

**Comment by ulivz** [comment]
Hey, thanks to the great work, we have set the default port of VuePress to 0.0.0.0 which is available at (>=1.0.0-alpha.45), let me know if it works for you.

**Comment by lbogdan** [comment]
@ulivz Great, thanks! Updates to `1.0.0-alpha.46` and it seems to be working: https://codesandbox.io/s/948mvov384 .

**Comment by SaraVieira** [comment]
Mergy 🎉🎉

**Pull request merged**
