### PR TITLE
make up on share modal

### PR DESCRIPTION
**Pull request by SaraVieira**
A cleaner look for the share modal

Issues:

Monaco does not load text

screenshot 2019-02-10 at 18 08 11
screenshot 2019-02-10 at 18 08 05
screenshot 2019-02-10 at 18 07 56

### CODE REVIEW

**Comment by CompuIves** [comment]
This is such a big improvement!

Some small points:

- I would rotate the expand arrows to make them consistent with the sidebar
- The font size of the headers can be a bit smaller, this will also vertically align them with the icons
- I think we can make the margin under the items (like Appearance) a bit less

**Comment by CompuIves** [comment]
Ohh the default view is far better!

**Comment by bazzjuh** [comment]
Looks good! A huge improvement from the current share modal.

Some points:
* rotate the expand arrows to make them consistent with the sidebar
* smaller margin under the items (like Appearance)
* smaller margin between embed preview and headers (configure & share)

**Comment by SaraVieira** [comment]
All fixed and also created a `title.js`to clean up the code a bit on the index.js

**Comment by SaraVieira** [comment]
closes https://github.com/CompuIves/codesandbox-client/issues/390

**Pull request merged**
