### PR TITLE
Read tab width from preferences.

### PR DESCRIPTION
**Pull request by ryanpcmcquen**
Closes https://github.com/CompuIves/codesandbox-client/issues/344.

Signed-off-by: Ryan P.C. McQuen <ryanpcmcquen@member.fsf.org>

**What kind of change does this PR introduce?**
Bug fix.

**What is the current behavior?**
Tab width settings are ignored.

**What is the new behavior?**
Tab width settings are respected.

**Checklist**:

- [ ] Documentation
- [ ] Tests
- [x] Ready to be merged 
- [x] Added myself to contributors table

### CODE REVIEW

**Comment by CompuIves** [comment]
Perfect @ryanpcmcquen! Thanks for opening this PR, welcome to the contributors club ;D

**Comment by ryanpcmcquen** [comment]
@CompuIves, thank you! When will this change be live on the site?

**Comment by CompuIves** [comment]
Should be live already :).

**Comment by ryanpcmcquen** [comment]
Nice!

**Pull request merged**
