### PR TITLE
Switch from react-tippy to @tippy.js/react for tooltips

### LINKED ISSUE #1582: Switch from react-tippy to @tippy.js/react for tooltips
# 🌈 Feature

CodeSandbox is using `react-tippy` for tooltips. I made the underlying `tippy.js` library which it uses, but not `react-tippy`.  I think it's using a version of tippy.js from 2017 – since then, many bugs have been fixed and features released. It's been iterated on/improved a lot and is much more stable and mature now in 2019.

[`@tippy.js/react`](https://github.com/atomiks/tippy.js-react) is the official React wrapper I released and is using the latest version (v4).

Some benefits out of the box:

- Smaller size compared to react-tippy
- Better appearance (animations are quicker, tooltips are smaller). The current ones feel quite large and slugglish at the moment. Technically you can fix this with react-tippy, but still
- Guaranteed updates (react-tippy is essentially unmaintained now)

Obviously there are quite a few breaking changes (tooltip DOM is different, React API is different), but I believe the switch should be worth it

### PR DESCRIPTION
**Pull request by SaraVieira**
This PR removes react-tippy to  @tippy.js/react

closes #1582 

@atomiks

### CODE REVIEW

**Comment by atomiks** [comment]
Nice work 🎉 

I think the manually controlled tooltips (e.g. update tooltip) might be missing the conversion over to the new API?

**Comment by atomiks** [comment]
https://github.com/CompuIves/codesandbox-client/blob/500b18c99e67f872748feaa54139af32251eb970/packages/app/src/app/pages/Sandbox/Editor/Header/UpdateFound/index.js

This will need to be updated to the new API. I'm not familiar with CodeSandbox codebase so maybe there are others too. Are there tests for this?

**Comment by SaraVieira** [comment]
@atomiks You mean this file: packages/app/src/app/pages/Sandbox/Editor/Header/UpdateFound/index.js?

**Comment by SaraVieira** [comment]
This is the only file that did contain new things that wern't known to me :/

What is the new API for open (isEnabled?) and trigger?

**Comment by atomiks** [comment]
- `open` => `isVisible`

That's it 😅

**Comment by SaraVieira** [comment]
Oh! Nice!

Done!

Also is this file okay?

https://github.com/CompuIves/codesandbox-client/blob/69b0360bed301f50327bd780138e7fa6eb5eb42f/packages/common/src/components/Tooltip.tsx

**Comment by atomiks** [comment]
I think you should be spreading the props into `<Tippy />` rather than the `<span>`. That would remove the need to repeat the props for every option you need

**Comment by SaraVieira** [comment]
That doesn't work because when I do that and have some option that is actually for styled components the app breaks saying that the option isn't valid :(

Example:

```
      <ActionTooltip
        disabledAction={!onClick}
        title={placeholder || tooltip}
      >
        <Icon />
      </ActionTooltip>
```

That disabled action is something for styled components but bad things happen


Event the style tags was breaking it :(

**Comment by atomiks** [comment]
You can destructure the invalid props out and only pass valid ones to tippy (assuming the invalid ones can be known beforehand)

**Comment by SaraVieira** [comment]
I don't because since we are using styled components you can pass anything.

I could know the valid ones and do it that way by going to the tippy website and destructure those

**Comment by atomiks** [comment]
There are almost 50 options so that would suck 😱 

But you could import the underlying library `tippy.js`.

It exposes the default options object on `tippy.defaults`, so you can loop through those keys to verify!

**Comment by SaraVieira** [comment]
Is there not a way to tell Tippy to ignore those things? And I pass style to the span?

**Comment by atomiks** [comment]
See my edit(s), I made like 100 of them 😰 

Does that answer your question?

**Comment by SaraVieira** [comment]
Sorry, edits where? :(

**Comment by atomiks** [comment]
https://github.com/CompuIves/codesandbox-client/pull/1584#issuecomment-470465638

**Comment by SaraVieira** [comment]
I think I am done, just need the new api for hideOnClick

**Comment by SaraVieira** [comment]
Ignore that ahah

**Comment by atomiks** [comment]
I think the `placement` destructure is not necessary, apart from that looks good

**Comment by SaraVieira** [comment]
It should all 100%

Fixed all the props because those props attached were not the best idea so they have been moved to a container and I passed style and css to the span :)

**Comment by SaraVieira** [comment]
> I think the placement destructure is not necessary, apart from that looks good

Removed 😄 

One last look?

Thank you :)

**Comment by atomiks** [comment]
I don't know how to test it but from my cursory glance it looks OK, I guess we should wait for @CompuIves  to approve ✅

**Comment by CompuIves** [comment]
Yes! I've been wanting to upgrade Tippy for a long time. 

This is quite a big change, so it will require some more testing. One thing I noticed is that for icons we only get a tooltip when we hover over the icon instead of over the container with this change. I assume this happens because all elements are now wrapped in a `span`:

screenshot 2019-03-07 at 11 53 12

Is there a way to retain the simplicity without a `span` wrap?

**Comment by atomiks** [comment]
I think the tooltips should be wrapping the buttons instead?

`react-tippy` used to use a wrapper `<div>` element which is what the tooltip was applied to

**Comment by SaraVieira** [comment]
That is probably a css issue, since react tippy used a div and a div is block but a span is not. 

Adding a div and setting always to 100% of the size fixes that @CompuIves :)

**Comment by CompuIves** [comment]
Nice! The icons work!

I found some layout problem here:

image

Other than that, works!

**Comment by SaraVieira** [comment]
Fixed 

screenshot 2019-03-07 at 14 00 27

**Comment by SaraVieira** [comment]
To be merged after editor redisign

**Comment by atomiks** [comment]
Great work on the redesign! I notice you're using tooltips with delays for buttons next to each other in the new design. The `<TippyGroup />` wrapper component is perfect for this use case

https://atomiks.github.io/tippyjs/misc/#groups

**Comment by CompuIves** [comment]
This can be merged after the conflicts are done! Good tip @atomiks, seems like exactly what we need!

**Comment by SaraVieira** [comment]
Duuude, I have no idea how to even start on these ahah

**Comment by lbogdan** [comment]
Ouch! 😄

**Comment by SaraVieira** [comment]
SHIP IT

**Comment by CompuIves** [comment]
YES! Thank you @atomiks and @SaraVieira!!

**Comment by SaraVieira** [comment]
Omg yay! One down! 6 to go

**Pull request merged**
