### PR TITLE
update new sandbox menu into a modal

### PR DESCRIPTION
**Pull request by Tushkiz**
This is an initial draft for the update in UI of our `New Sandbox` menu

### CODE REVIEW

**Comment by Tushkiz** [comment]
menu-updated

**Comment by CompuIves** [comment]
Woooow this is really really really cool! Can't wait to merge this in. There are some remaining linting issues.

**Comment by CompuIves** [comment]
Okies! I did a small addition to the background hover effect. The last thing that needs to be done is cleanup of the old menu, could you delete NewSandboxMenu and related files?

**Comment by Tushkiz** [comment]
The background hover effect looks great. 💯

**Comment by lbogdan** [comment]
Looking dope, guys! :heart_eyes:

**Pull request merged**
