### PR TITLE
Get latest publications on the homepage from medium

### PR DESCRIPTION
**Pull request by SaraVieira**

### CODE REVIEW

**Comment by CompuIves** [comment]
Woooow this solves one of my biggest pains! 😍

**Comment by SaraVieira** [comment]
Life is so much better when you find Gatsby source plugins man

**Comment by CompuIves** [comment]
I'm thinking that it would be good to improve the styling of the publication images: 
image

They now have variable heights, which makes it look a bit messy. Maybe find a way to make them seem to have the same height?

**Comment by SaraVieira** [comment]
shhhhhhhhhhhhh

Do you Know anyone at medium ?

because I don't know their sizes ? :(

**Comment by CompuIves** [comment]
Yay!

**Pull request merged**
