### PR TITLE
Add tsx to test detection list, update and add missing flow types

### LINKED ISSUE #677: Proposal: add ability to run tests or add a documentation how todo so
It would be very handy if it will be possible to run tests

### PR DESCRIPTION
**Pull request by FDiskas**
**What kind of change does this PR introduce?**
Updated types for flow, added missing ones or generated new
Added `.tsx` to the extension list for tests detection
Edited files [jest-lite.js](https://github.com/CompuIves/codesandbox-client/pull/679/files#diff-10), [jest-lite.test.js](https://github.com/CompuIves/codesandbox-client/pull/679/files#diff-11)

**What is the current behavior?**
Currently we can't have *.tsx tests in projects
example: https://codesandbox.io/s/q9624qv3x9

**What is the new behavior?**
It should detect test cases with `.tsx` extentions

Closes #677

**Checklist**:

- [ ] Documentation
- [x] Tests
- [x] Ready to be merged 
- [x] Added myself to contributors table

### CODE REVIEW

**Comment by FDiskas** [comment]
**502 Bad Gateway** on sandbox :(

**Comment by CompuIves** [comment]
Interesting, still right now? Our alert system doesn't notice any 502s currently.

**Comment by CompuIves** [comment]
Oh on the staging you mean? I briefly had a heart attack 😅. 

I can take a look at the PR tomorrow first thing, it looks good from a quick glance!

**Comment by CompuIves** [comment]
Perfect! Could you remove the `flow-typed` changes from the diff? That makes it easier to reckon with the changes. Should be as simple as doing `git checkout master flow-typed`.

**Comment by FDiskas** [comment]
@CompuIves not sure what you mean by `git checkout master flow-typed` but i just reverted modified flow types :clubs:

**Comment by FDiskas** [comment]
Probably I can add another pull requests with some postinstall script to update flow-types

**Comment by CompuIves** [comment]
Perfect! Thanks for the PR. 

> Probably I can add another pull requests with some postinstall script to update flow-types

Yeah I think we could use a PR with updated flowtypes generally. Does it make sense to update them after every install?

**Comment by FDiskas** [comment]
@CompuIves probably yes. I don't know better solution. Yes it's sucks wait to finish updating flow-types on each installation. :smiling_imp:
In other case types can easy become outdated :loudspeaker:

**Pull request merged**
