### PR TITLE
Sort dependency versions

### PR DESCRIPTION
**Pull request by yesmeck**
**What kind of change does this PR introduce?**

Ehancement

**What is the current behavior?**

screen shot 2018-02-12 at 15 08 40

**What is the new behavior?**

screen shot 2018-02-12 at 15 08 01

**Checklist**:

- [x] Documentation
- [x] Tests
- [x] Ready to be merged 
- [x] Added myself to contributors table

### CODE REVIEW

**Comment by CompuIves** [comment]
This looks very good! I'll do some quick extra testing when the Algolia index is back up again (the index of Algolia cleared because of an error today).

**Comment by CompuIves** [comment]
Hmm, it seems like this PR hasn't been deployed yet. Could you make an empty commit to force deployment @yesmeck? I want to check how eg. `next` tags are handled.

**Comment by lbogdan** [comment]
@CompuIves I rebuilt it, you can check now.

**Comment by CompuIves** [comment]
Perfect! Looks good to me!

**Pull request merged**
