### PR TITLE
CxJS template

### PR DESCRIPTION
**Pull request by mstijak**
**What kind of change does this PR introduce?**
Adds a new template for CxJS (#628)

**What is the current behavior?**

**What is the new behavior?**

**Checklist**:

- [ ] Documentation
- [ ] Tests
- [ ] Ready to be merged 
- [ ] Added myself to contributors table 

It took me a while, but it actually wasn't that hard. Please let me know what's the next step.

### CODE REVIEW

**Comment by CompuIves** [comment]
Ah, is this based on the recent changes I did on master?

**Comment by mstijak** [comment]
Yes, it is. Icon was removed from template registration and it took me some
time to discover that after rebasing.

**Comment by CompuIves** [comment]
Ah yes, I'm sorry for that! Great to see another template! I'm planning on merging the new templates (Dojo 2 and CxJS) in this Thursday.

**Comment by mstijak** [comment]
Great. The only issue I see is with creating a new sandbox. Is that something that you'll handle? Do you need a "Hello World" sample for CxJS?

**Comment by CompuIves** [comment]
It's in! :D

**Pull request closed without merging**
