### PR TITLE
Improve button styling on hover

### PR DESCRIPTION
**Pull request by jdonor**
Increase the contrast between the text and the background while in the hover state. The white text was pretty hard to see on the light orange background.

**What kind of change does this PR introduce?**
Visual fix

**What is the current behavior?**
image

**What is the new behavior?**
image

**Checklist**:

- [ ] Documentation N/A
- [ ] Tests - wasn't able to run these due to the script erroring out
- [x] Ready to be merged 
- [x] Added myself to contributors table

### CODE REVIEW

**Comment by jdonor** [comment]
Looks like the tests are failing due to the button snapshots not getting updated. I'm looking into why the yarn test scripts aren't working for me.

**Comment by jdonor** [comment]
I'm getting the following error log. If someone has any insight that would be great!
```
0 info it worked if it ends with ok
1 verbose cli [ '/home/josiah/.nvm/versions/node/v9.4.0/bin/node',
1 verbose cli   '/home/josiah/.nvm/versions/node/v9.4.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'test' ]
2 info using npm@5.6.0
3 info using node@v9.4.0
4 verbose run-script [ 'pretest', 'test', 'posttest' ]
5 info lifecycle app@0.1.1~pretest: app@0.1.1
6 info lifecycle app@0.1.1~test: app@0.1.1
7 verbose lifecycle app@0.1.1~test: unsafe-perm in lifecycle true
8 verbose lifecycle app@0.1.1~test: PATH: /home/josiah/.nvm/versions/node/v9.4.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/josiah/Dev/open-source/codesandbox-client/packages/app/node_modules/.bin:/home/josiah/Dev/open-source/codesandbox-client/packages/app/node_modules/.bin:/home/josiah/Dev/open-source/codesandbox-client/packages/node_modules/.bin:/home/josiah/Dev/open-source/codesandbox-client/node_modules/.bin:/home/josiah/Dev/open-source/node_modules/.bin:/home/josiah/Dev/node_modules/.bin:/home/josiah/node_modules/.bin:/home/node_modules/.bin:/node_modules/.bin:/home/josiah/.nvm/versions/node/v9.4.0/bin:/home/josiah/Dev/open-source/codesandbox-client/node_modules/.bin:/home/josiah/.config/yarn/link/node_modules/.bin:/home/josiah/Dev/open-source/codesandbox-client/node_modules/.bin:/home/josiah/Dev/open-source/codesandbox-client/node_modules/.bin:/home/josiah/.config/yarn/link/node_modules/.bin:/home/josiah/Dev/open-source/codesandbox-client/node_modules/.bin:/home/josiah/.yarn/bin:/home/josiah/.nvm/versions/node/v9.4.0/libexec/lib/node_modules/npm/bin/node-gyp-bin:/home/josiah/.nvm/versions/node/v9.4.0/lib/node_modules/npm/bin/node-gyp-bin:/home/josiah/.nvm/versions/node/v9.4.0/bin/node_modules/npm/bin/node-gyp-bin:/home/josiah/.rvm/rubies/default/bin:/home/josiah/.rvm/bin:/home/josiah/.rvm/gems/ruby-2.3.4/bin:/home/josiah/.nvm/versions/node/v9.4.0/bin:/home/josiah/bin:/home/josiah/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle app@0.1.1~test: CWD: /home/josiah/Dev/open-source/codesandbox-client/packages/app
10 silly lifecycle app@0.1.1~test: Args: [ '-c', 'jest --env=jsdom' ]
11 silly lifecycle app@0.1.1~test: Returned: code: 1  signal: null
12 info lifecycle app@0.1.1~test: Failed to exec test script
13 verbose stack Error: app@0.1.1 test: `jest --env=jsdom`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/josiah/.nvm/versions/node/v9.4.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:160:13)
13 verbose stack     at ChildProcess.<anonymous> (/home/josiah/.nvm/versions/node/v9.4.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:160:13)
13 verbose stack     at maybeClose (internal/child_process.js:943:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid app@0.1.1
15 verbose cwd /home/josiah/Dev/open-source/codesandbox-client/packages/app
16 verbose Linux 4.13.0-37-generic
17 verbose argv "/home/josiah/.nvm/versions/node/v9.4.0/bin/node" "/home/josiah/.nvm/versions/node/v9.4.0/bin/npm" "run" "test"
18 verbose node v9.4.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error app@0.1.1 test: `jest --env=jsdom`
22 error Exit status 1
23 error Failed at the app@0.1.1 test script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by CompuIves** [comment]
This is really good, I think the buttons generally have incorrect styling. I'd like the buttons to have a more similar style as the Live button:

screen shot 2018-04-03 at 15 19 51

I quickly made a small mockup of what it could be:

screen shot 2018-04-03 at 15 19 07

Maybe this is the right moment to restyle our buttons altogether. What do you think @bazzjuh?

**Comment by bazzjuh** [comment]
The mockup of the buttons looks good! This restyle will add more consistency for the buttons.

**Comment by ValentinH** [comment]
@jdonor In which folder do you run the tests and with which command?

**Comment by CompuIves** [comment]
> If you want I can incorporate those changes into this pull request.

That sounds good!

Hmm, I believe #588 will remove the Button style tests. So I think you can remove them as well instead of having the hassle of updating all snapshots.

**Comment by jdonor** [comment]
@ValentinH I'm running ```yarn test``` in the root of the repo.

@CompuIves I'll look into removing the button tests as well. Would still be nice in general to be able to run the tests locally.

**Comment by ValentinH** [comment]
You might want to try running `yarn test` in the `packages/app` folder. I had a similar issue in the past.

**Comment by jdonor** [comment]
Thanks @ValentinH, that seems to have fixed my issue with running the tests. Should we add a note somewhere (maybe the contributing guide) to help others out when getting started?

**Comment by lbogdan** [comment]
@jdonor , @CompuIves 
Just wanted to let you know I built this PR, you can check it here http://pr690.cs.lbogdan.tk/s/new . (the build server was down when this PR was created)

**Pull request closed without merging**
