### PR TITLE
Show/Hide Sidebar workspace item using React Show

### PR DESCRIPTION
**Pull request by BilalBudhani**
I wanted to start contributing to Codesandbox project and was keenly looking for some issue to start from, I saw this one https://github.com/CompuIves/codesandbox-client/issues/358 interesting enough to work –– So I picked it up. After some fiddling around I got the expected behaviour described in the issue mentioned earlier. 

Looking forward for some feedback from the maintainers. 

Thanks.

### CODE REVIEW

**Comment by lbogdan** [comment]
Hey @BilalBudhani , that's very nice! While playing around with it, I've noticed that the "Dependecies" section (maybe because it's the last one?) opens fine, but closes without the animation. Can you maybe take a look at that? Thanks!

**Comment by BilalBudhani** [comment]
Hey, @lbogdan thanks for the feedback. I just compared the behaviour of collapsing/uncollapsing between this version and codesandbox.io production version –– I can see the animation taking place in "Dependencies" section. Perhaps, the animation is being performed under 200ms and the height is relatively large than other sections that is why it is hard to differentiate (?). Do you want me to increase the animation time to 250-300ms?

**Comment by lbogdan** [comment]
It's not that, I've tried with animations slowed down to 10%, it just hides without any animation:

**Comment by BilalBudhani** [comment]
@lbogdan you were right, it was not animating –– I had to increase the animating time to catch this issue, Good catch! Thanks. 

I implemented a fix, turns out `keepState` props was making the `children` component unmount before the animation even start. Therefore, I delegated the unmounting task to React-Show library (Check `unmountOnHide` property https://github.com/react-tools/react-show#usage).

**Comment by CompuIves** [comment]
I love this! Thanks @BilalBudhani, I'll review this after dinner and merge it in if all is good 😄 .

**Comment by tannerlinsley** [comment]
BTW - I just released React-show 2.0. Upgrade should be seamless, given you're not using any deprecated props.  Upgrade for some more stability!

**Comment by BilalBudhani** [comment]
@tannerlinsley Sure, I will look into upgrading to 2.0 this weekend. Thanks for informing about the upgrade availability.

**Comment by tannerlinsley** [comment]
You bet

**Pull request merged**
