### PR TITLE
Add Nest SSE template

### PR DESCRIPTION
**Pull request by tomkuehl**
**What kind of change does this PR introduce?**
A Nest (https://nestjs.com/) SSE template

**Checklist**:
- [x] Ready to be merged

**Dependencies**
This PR depends on the following PR to map github imports to the nest template:
https://github.com/codesandbox-app/codesandbox-importers/pull/18

### CODE REVIEW

**Comment by kamilmysliwiec** [comment]
Can't wait! +1

**Comment by tomkuehl** [comment]
As discussed in Discord it's ready to merge now.

**Comment by kamilmysliwiec** [comment]
Awesome 🔥 Perfect job

**Comment by SaraVieira** [comment]
@compulves can this be merged ?

**Comment by CompuIves** [comment]
Thank you so much for the work on this @tomkuehl!

**Comment by kamilmysliwiec** [comment]
Any ETA when it is gonna be deployed? 🚀 I would love to give it a shot :)

**Comment by CompuIves** [comment]
We're releasing it today!

**Comment by kamilmysliwiec** [comment]
Boooom 💥

**Pull request merged**
